import { Inter } from "next/font/google";
import { NavBar} from "../../Components/navbar";
import './globals.css';
import { Bodypart } from "./page.module.css";
import SearchMovie from "../../search/page"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'home page',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
  

    <html lang="en">
      <body className={ Bodypart }>
      <NavBar/>
    <SearchMovie/>
        {children}
        </body>
    </html>
  )
};

